boringssl: delete local patch [ci skip]
Though the `undefined reference to `_setjmp'` issue still reproduces,
it no longer seems to affect curl + boringssl builds.