make `CW_DEV_CROSSMAKE_REPRO` compatible with Xcode [ci skip]
This option enables `_clean-lib.sh` on all created static libs to
improve their reproducibility across build tools.

It had these issues when using Apple Xcode's built-in `ar` tool:
- doesn't support an `--output` option.
- doesn't support `D` option/command on create
  (to use zero for timestamps and uids/gids).
- `ar x` creates files `__.SYMDEF` and `__.SYMDEF SORTED` where
  the space caused issues with our script.

On the surface this caused `HAVE_STRUCT_TIMEVAL` detection to fail,
which in turn causes this error on compile:
```
./lib/curl_setup_once.h:113:8: error: redefinition of 'timeval'
```

Solutions:
- pass binutils flavour ("apple") to `_clean-lib.sh`.
- for apple binutils fall back to a recently deleted logic to avoid
  the need for option `--output`. With the twist of using `readlink -f`
  instead of `realpath` to avoid relying on the extra `coreutils`
  package from Homebrew. This in turn requires macOS Monterey, which
  is the first macOS shipping with `readlink`.
- fix the script to work with filenames with spaces in them.
  (It also seems safe to delete `__.SYMDEF*` after `ar x`; these are
  metadata re-generated by `ar c` anyway.)