add support for AWS-LC TLS-backend (broken for Windows)
From a build perspective it behaves almost exactly like BoringSSL, and
we're assuming the same codepaths by default.

AWC-LC has a built-in way to skip building tests and command-line tools.
We do use that. It also has versioned releases and a way to retrieve
this version number at build-time, so no need for the commit hash hack
we use with BoringSSL.

It suffers from the same pthread dependency issue on Windows, by the
looks of its source code.

Actual testing on Windows reveals that the project no longer compiles
with llvm-mingw:

```
awslc/crypto/refcount_win.c:23:15: error: expected parameter declarator
static_assert(alignof(CRYPTO_refcount_t) == alignof(LONG),
              ^
```

It means we lost BoringSSL for Windows and also AWS-LC. Comments tell
that their team only tests Visual Studio, though they were open for
other compilers. That was in 2021.

This patch is experimental and AWS-LC support might be removed in the
future.