_build.sh: disable `-ftrivial-auto-var-init=zero` for macOS gcc-16 arm64 [ci skip]
Due to causing false positive `-Wmaybe-uninitialized`.

Ref: https://github.com/curl/curl/pull/22209 (tests to narrow it down)

```
/Users/runner/work/curl-for-win/curl-for-win/curl/lib/http.c:207:6: error: 'out.str' may be used uninitialized [-Werror=maybe-uninitialized]
  207 |   if(header_has_value(&header, &out)) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/curl-for-win/curl-for-win/curl/lib/http.c: In function 'Curl_http':
/Users/runner/work/curl-for-win/curl-for-win/curl/lib/http.c:186:19: note: 'out.str' was declared here
  186 |   struct Curl_str out;
      |                   ^~~
In function 'copy_custom_value',
    inlined from 'http_add_connection_hd' at /Users/runner/work/curl-for-win/curl-for-win/curl/lib/http.c:2791:16,
    inlined from 'http_add_hd' at /Users/runner/work/curl-for-win/curl-for-win/curl/lib/http.c:3005:14,
    inlined from 'Curl_http' at /Users/runner/work/curl-for-win/curl-for-win/curl/lib/http.c:3083:14:
/Users/runner/work/curl-for-win/curl-for-win/curl/lib/http.c:207:6: error: 'out.len' may be used uninitialized [-Werror=maybe-uninitialized]
  207 |   if(header_has_value(&header, &out)) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/curl-for-win/curl-for-win/curl/lib/http.c: In function 'Curl_http':
/Users/runner/work/curl-for-win/curl-for-win/curl/lib/http.c:186:19: note: 'out.len' was declared here
  186 |   struct Curl_str out;
      |                   ^~~
```
Ref: https://github.com/curl/curl-for-win/actions/runs/29448506817/job/87464901787
Ref: https://github.com/curl/curl/actions/runs/29958777720/job/89054416774?pr=22209