_build.sh: add support for standard gcc for mac [ci skip]
Specifically gcc provided via Homebrew. This package doesn't ship with
binutils, so for now this build mode relies on Xcode tools. This means
they suffer from the same reproducibility bugs as Apple clang builds.

Must supply this to enable:
export CW_CCSUFFIX='-13'

Optional:
export CW_CONFIG='-gcc'

Follow-up to 5add6165606c80b193b661a71f2b400b5ffc298e

Build is broken with the latest Xcode and CommandLineTools,
due to this:
  https://github.com/curl/curl/issues/10356

```
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/dispatch/dispatch.h:28,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:17,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:66,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCDynamicStoreCopySpecific.h:30,
                 from .../curl/lib/macos.c:33,
                 from .../curl/bld-cmake-gcc-x64-sys/lib/CMakeFiles/libcurl_object.dir/Unity/unity_0_c.c:241:
/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/os/object.h:275:1: error: expected ';' before 'extern'
  275 | OS_EXPORT OS_SWIFT_UNAVAILABLE("Can't be used with ARC")
      | ^~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/os/clock.h:14:1: error: expected ';' before 'typedef'
   14 | OS_ENUM(os_clockid, uint32_t,
      | ^~~~~~~
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/os/workgroup.h:29,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/dispatch/dispatch.h:64:
/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/os/workgroup_base.h:67:1: error: expected ';' before 'struct'
   67 | struct OS_REFINED_FOR_SWIFT os_workgroup_attr_opaque_s {
      | ^~~~~~
[...]
```

The root cause is not Xcode itself but the default SDK it's pointing to.
With SDK 12 it compiles without error. The failure above is with SDK 13,
the default SDK since Xcode 14.