fix quictls tarball and build [ci skip]
1. somehow the hash of the original tarball no longer matched
2. the build failed with this:

```
../ssl/ssl_quic.c:207:5: error: use of undeclared identifier 'offset'
  207 |     offset = sc->quic_buf->length;
      |     ^
../ssl/ssl_quic.c:208:37: error: use of undeclared identifier 'offset'
  208 |     if (!BUF_MEM_grow(sc->quic_buf, offset + len)) {
      |                                     ^
../ssl/ssl_quic.c:212:33: error: use of undeclared identifier 'offset'
  212 |     memcpy(sc->quic_buf->data + offset, data, len);
      |                                 ^
../ssl/ssl_quic.c:237:13: error: no member named 'start' in 'struct quic_data_st'
  237 |         qd->start = sc->quic_next_record_start;
      |         ~~  ^
4 errors generated.
```

Switch to a tag with the same version that builds correctly.