add linux musl cross-build llvm clang-rt support [ci skip]
llvm did not work with libgcc in these scenarios due to header
confusion in zstd [1][2] and an odd linker error in curl [3]. Thus,
switching to clang-rt turned out to be requirement (that I wanted
to do anyway.)

[1] https://github.com/curl/curl-for-win/actions/runs/6697330946/job/18196968873#step:3:2527
```
[  9%] Building C object lib/CMakeFiles/libzstd_static.dir/home/runner/work/curl-for-win/curl-for-win/zstd/lib/common/entropy_common.c.o
In file included from /home/runner/work/curl-for-win/curl-for-win/zstd/lib/common/error_private.c:13:
In file included from /home/runner/work/curl-for-win/curl-for-win/zstd/build/cmake/../../lib/common/error_private.h:25:
In file included from /home/runner/work/curl-for-win/curl-for-win/zstd/build/cmake/../../lib/common/compiler.h:211:
/usr/lib/gcc-cross/aarch64-linux-gnu/13/include/arm_neon.h:40:9: error: unknown type name '__Int8x8_t'; did you mean '__int128_t'?
typedef __Int8x8_t int8x8_t;
        ^
note: '__int128_t' declared here
/usr/lib/gcc-cross/aarch64-linux-gnu/13/include/arm_neon.h:41:9: error: unknown type name '__Int16x4_t'
typedef __Int16x4_t int16x4_t;
        ^
[...]
```

[2]
```
[  6%] Building C object lib/CMakeFiles/libzstd_static.dir/.../zstd/lib/common/entropy_common.c.o
In file included from /.../zstd/lib/common/entropy_common.c:18:
In file included from /.../zstd/build/cmake/../../lib/common/mem.h:22:
In file included from /.../zstd/build/cmake/../../lib/common/compiler.h:209:
In file included from /usr/lib/gcc-cross/x86_64-linux-gnu/12/include/emmintrin.h:31:
/usr/lib/gcc-cross/x86_64-linux-gnu/12/include/xmmintrin.h:52:1: error: conflicting types for '_mm_prefetch'
_mm_prefetch (const void *__P, enum _mm_hint __I)
^
/usr/lib/gcc-cross/x86_64-linux-gnu/12/include/xmmintrin.h:52:1: note: '_mm_prefetch' is a builtin with type 'void (const char *, int)'
/usr/lib/gcc-cross/x86_64-linux-gnu/12/include/xmmintrin.h:54:3: error: argument to '__builtin_prefetch' must be a constant integer
  __builtin_prefetch (__P, (__I & 0x4) >> 2, __I & 0x3);
  ^                        ~~~~~~~~~~~~~~~~
/usr/lib/gcc-cross/x86_64-linux-gnu/12/include/xmmintrin.h:130:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
  return (__m128) __builtin_ia32_addss ((__v4sf)__A, (__v4sf)__B);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[...]
```

[3] https://github.com/curl/curl-for-win/actions/runs/6700425399/job/18206341211#step:3:5927
```
ld.lld-16: error: /usr/lib/aarch64-linux-musl/libc.a(sigsetjmp.lo):(.text+0x0): relocation R_AARCH64_CONDBR19 out of range: 2120920 is not in [-1048576, 1048575]; references setjmp
>>> defined in /usr/lib/aarch64-linux-musl/libc.a(setjmp.lo)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/CMakeFiles/libcurl_shared.dir/build.make:96: lib/libcurl.so.4.8.0] Error 1
```