curl-cmake.sh: restore `-Wl,--start-group` for non-Windows
This was required for alpine (v3.18) gcc musl builds,
otherwise this happened:
```
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /home/runner/work/curl-for-win/curl-for-win/libssh2/x64-musl/usr/lib/libssh2.a(comp.o): in function `comp_method_zlib_dtor':
6291
(.text+0x151): undefined reference to `deflateEnd'
6292
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /home/runner/work/curl-for-win/curl-for-win/libssh2/x64-musl/usr/lib/libssh2.a(comp.o): in function `comp_method_zlib_comp':
6293
(.text+0x3ae): undefined reference to `deflate'
6294
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /home/runner/work/curl-for-win/curl-for-win/libssh2/x64-musl/usr/lib/libssh2.a(comp.o): in function `comp_method_zlib_init':
6295
(.text+0x4d5): undefined reference to `deflateInit_'
6296
collect2: error: ld returned 1 exit status
```

Do not do this with Apple clang.