ngtcp2.sh: add workaround for QUICTLS API detection [ci skip]
Sadly the gcc ld issue hit again, and requires and additional hack to make
detection work in ngtcp2.

Fixes:
```
/usr/local/Cellar/mingw-w64/12.0.0_1/toolchain-i686/bin/i686-w64-mingw32-ld: curl/openssl/_x86-win-ucrt/usr/lib/libcrypto.a(libdefault-lib-winstore_store.obj):(.text$winstore_close+0x1a): undefined reference to `_imp__CertFreeCertificateContext@4'
/usr/local/Cellar/mingw-w64/12.0.0_1/toolchain-i686/bin/i686-w64-mingw32-ld: curl/openssl/_x86-win-ucrt/usr/lib/libcrypto.a(libdefault-lib-winstore_store.obj):(.text$winstore_close+0x3f): undefined reference to `_imp__CertCloseStore@8'
/usr/local/Cellar/mingw-w64/12.0.0_1/toolchain-i686/bin/i686-w64-mingw32-ld: curl/openssl/_x86-win-ucrt/usr/lib/libcrypto.a(libdefault-lib-winstore_store.obj):(.text$winstore_open+0x66): undefined reference to `_imp__CertOpenSystemStoreW@8'
/usr/local/Cellar/mingw-w64/12.0.0_1/toolchain-i686/bin/i686-w64-mingw32-ld: curl/openssl/_x86-win-ucrt/usr/lib/libcrypto.a(libdefault-lib-winstore_store.obj):(.text$winstore_open+0x80): undefined reference to `_imp__CertFreeCertificateContext@4'
/usr/local/Cellar/mingw-w64/12.0.0_1/toolchain-i686/bin/i686-w64-mingw32-ld: curl/openssl/_x86-win-ucrt/usr/lib/libcrypto.a(libdefault-lib-winstore_store.obj):(.text$winstore_load+0x23b): undefined reference to `_imp__CertFindCertificateInStore@24'
/usr/local/Cellar/mingw-w64/12.0.0_1/toolchain-i686/bin/i686-w64-mingw32-ld: curl/openssl/_x86-win-ucrt/usr/lib/libcrypto.a(libdefault-lib-winstore_store.obj):(.text$winstore_set_ctx_params+0x12a): undefined reference to `_imp__CertFreeCertificateContext@4'
/usr/local/Cellar/mingw-w64/12.0.0_1/toolchain-i686/bin/i686-w64-mingw32-ld: curl/openssl/_x86-win-ucrt/usr/lib/libcrypto.a(libdefault-lib-winstore_store.obj):(.text$winstore_set_ctx_params+0x1cf): undefined reference to `_imp__CertFindCertificateInStore@24'
collect2: error: ld returned 1 exit status
```

Fixed upstream for the next release:
https://github.com/ngtcp2/ngtcp2/commit/48cba1d21c126070c4fe13c5cfd7b87f7f9f1e09
https://github.com/ngtcp2/ngtcp2/pull/1624