cares.sh: add workaround for `connectx` fallout on macOS [ci skip]
Symbol gets detected, but fails when trying to use while targeting an older
macOS version:

```
+ cmake -B _a64-mac-sys-bld -Wno-dev -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9
  -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_INSTALL_MESSAGE=NEVER -DCMAKE_INSTALL_PREFIX=/usr
  -DCMAKE_C_COMPILER=clang -DCMAKE_IGNORE_PREFIX_PATH=/opt/homebrew
  -DCMAKE_OSX_SYSROOT=/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk
  -DCMAKE_C_COMPILER_TARGET=aarch64-apple-darwin -DCARES_STATIC=ON -DCARES_STATIC_PIC=ON
  -DCARES_SHARED=OFF -DCARES_BUILD_TESTS=OFF -DCARES_BUILD_CONTAINER_TESTS=OFF -DCARES_BUILD_TOOLS=OFF
  '-DCMAKE_C_FLAGS= -Wno-unused-command-line-argument  -mmacosx-version-min=10.9 -fno-omit-frame-pointer
  -mbranch-protection=standard -fvisibility=hidden -fno-unwind-tables -fno-asynchronous-unwind-tables -Wl,-ld_new'
[...]
-- Looking for connectx
-- Looking for connectx - found
[...]
/Users/runner/work/curl-for-win/curl-for-win/cares/src/lib/ares_set_socket_functions.c:349:12: error: 'connectx' is only available on macOS 10.11 or newer [-Werror,-Wunguarded-availability]
[ 32%] Building C object src/lib/CMakeFiles/c-ares.dir/ares_socket.c.o
    return connectx(sock, &endpoints, SAE_ASSOCID_ANY,
           ^~~~~~~~
[ 33%] Building C object src/lib/CMakeFiles/c-ares.dir/ares_sortaddrinfo.c.o
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/sys/socket.h:752:5: note: 'connectx' has been marked as being introduced in macOS 10.11 here, but the deployment target is macOS 10.9.0
int connectx(int, const sa_endpoints_t *, sae_associd_t, unsigned int,
    ^
/Users/runner/work/curl-for-win/curl-for-win/cares/src/lib/ares_set_socket_functions.c:349:12: note: enclose 'connectx' in a __builtin_available check to silence this warning
    return connectx(sock, &endpoints, SAE_ASSOCID_ANY,
           ^~~~~~~~
1 error generated.
```
https://github.com/curl/curl-for-win/actions/runs/12969352173/job/36173290961#step:3:2490