GHA: re-sync with gcc-15 in mac-gcc job [ci skip]
Fixing:
```
+ brew install cosign gcc
gcc 14.2.0_1 is already installed but outdated (so it will be upgraded).
[...]
==> Upgrading gcc
  14.2.0_1 -> 15.1.0
==> Pouring gcc--15.1.0.arm64_sonoma.bottle.tar.gz
[...]
++ gcc-14 -dumpversion
./_build.sh: line 791: gcc-14: command not found
Error: Process completed with exit code 127.
```
Ref: https://github.com/curl/curl-for-win/actions/runs/15261316346/job/42919582303#step:3:1339