mbedtls.sh: fix linux arm64 cross-os-builds [ci skip]
Seen when cross-building from macOS:
```
[  9%] Building C object library/CMakeFiles/mbedcrypto.dir/aesce.c.o
./mbedtls/library/aesce.c:87:10: fatal error: asm/hwcap.h: No such file or directory
   87 | #include <asm/hwcap.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
```

It's most likely happening in other cross-combinations. The case
looks similar to OpenSSL using kernel headers.

It seems like a regression in mbedtls v3.4.0.