_ci-linux-alpine.sh: install gpg-agent to avoid error [ci skip]
Yet another odd issue with an odd fix.

After enabling GPG key verification for ngtcp2, Alpine started failing:
```
[GNUPG:] KEY_CONSIDERED F4F3B91474D1EB29889BD0EF7E8403D5D673C366 0
[GNUPG:] IMPORTED 7E8403D5D673C366 [...]
[GNUPG:] IMPORT_OK 1 F4F3B91474D1EB29889BD0EF7E8403D5D673C366
gpg: error running '/usr/bin/gpg-agent': probably not installed
gpg: failed to start gpg-agent '/usr/bin/gpg-agent': Configuration error
gpg: can't connect to the gpg-agent: Configuration error
gpg: Total number processed: 1
gpg:               imported: 1
[GNUPG:] IMPORT_RES 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0
Error: Process completed with exit code 2.
```
Ref: https://github.com/curl/curl-for-win/actions/runs/8329221019/job/22791045512#step:3:823

Installing `gpg-agent` fixes it. We're already doing this on Debian.

Another possible fix is installing `gnupg` instead of `gpg`, which
includes all gpg dependencies.