libressl.sh: force `strndup` off on Windows [ci skip]
mingw-w64-crt v15 4761eabdda9764d14778a52a4a9dd1d5e720569e (2026-04-12)
started offering it, picked up by llvm-mingw 20260421 (22.1.4), which
made LibreSSL detect it and use it. This caused this link error when
trying to use libcrypto.a with toolchains using stable mingw-w64 v14 or
anything older than the commit hash above:
```
C:/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/15.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe:
  curl\lib\libcrypto.a(bs_cbs.c.obj):bs_cbs.c:(.text$CBS_strdup[CBS_strdup]+0x4a):
  undefined reference to `strndup'
```

Refs:
https://mingw.googlesource.com/mingw-w64/+/4761eabdda9764d14778a52a4a9dd1d5e720569e
https://github.com/mstorsjo/llvm-mingw/releases/tag/20260421

Reported-by: Morten MacFly
Fixes: https://github.com/curl/curl-for-win/issues/101