boringssl: drop pthread hack [ci skip]
Though the `undefined reference to `_setjmp'` mingw-64/llvm bug still
reproduces with a minimal example, the issue no longer seems to affect
boringssl build. Reasons undiscovered.

This patch deletes the ugly hack that forced linking the pthread lib
dynamically.

curl now builds with vanilla boringssl using both llvm-mingw and
llvm + mingw-w64.

But, this time the resulting curl crashes when trying to do e.g.
`curl -v https://example.net/`. Reasons undiscovered.

ASM also needs to be disabled to avoid missing symbols.

BoringSSL support remains a giant mess for now.