curl: fix wolfSSL builds [ci skip]
curl no longer built with wolfSSL (5.5.4), due to missing uint8_t and
other C99 types:

```
In file included from curl_ntlm_core.c:72:
In file included from ../../wolfssl/x64-ucrt/usr/include/wolfssl/openssl/ssl.h:1647:
../../wolfssl/x64-ucrt/usr/include/wolfssl/quic.h:60:41: error: unknown type name 'uint8_t'
                                  const uint8_t* read_secret,
                                        ^
```

Till we find the cause, let's define the macro that makes wolfSSL
headers pull in these types.

Also add -lcrypt32 for autotools and CMake to make auto-detection
tests and presumably the final link work.

cmake:
```
curl 8.0.0-DEV (x86_64-w64-mingw32) libcurl/8.0.0-DEV wolfSSL/5.5.4 (Schannel) zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 WinIDN libssh2/1.10.1_DEV nghttp2/1.50.0 ngtcp2/0.13.1 nghttp3/0.6.0 libgsasl/2.2.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets zstd
```