curl: silence false positives with linux cross-build from mac [ci skip]
This has been discussed earlier with the curl team and concluded
these are false positives. Silencing them in code is not practical,
and it only affects a narrow build case.

Therefore this patch silences it within the narrow build case by
making this warning a non-error.

This makes it possible to enable `werror` by default.

```
curl/lib/vquic/curl_ngtcp2.c: In function 'cf_ngtcp2_send':
curl/lib/vquic/curl_ngtcp2.c:1511:38: error: potential null pointer dereference [-Werror=null-dereference]
 1511 |     nva[i].value = (unsigned char *)e->value;
      |                                     ~^~~~~~~
curl/lib/vquic/curl_ngtcp2.c:1510:23: error: potential null pointer dereference [-Werror=null-dereference]
 1510 |     nva[i].namelen = e->namelen;
      |                      ~^~~~~~~~~
curl/lib/vquic/curl_ngtcp2.c:1509:37: error: potential null pointer dereference [-Werror=null-dereference]
 1509 |     nva[i].name = (unsigned char *)e->name;
      |                                    ~^~~~~~
curl/lib/vquic/curl_ngtcp2.c:1512:24: error: potential null pointer dereference [-Werror=null-dereference]
 1512 |     nva[i].valuelen = e->valuelen;
      |                       ~^~~~~~~~~~
```
Ref: https://github.com/curl/curl-for-win/actions/runs/16525969694/job/46739239259#step:3:4981

(same for curl_quiche.c, curl_osslq.c, curl_msh3.c)

Ref: https://github.com/curl/curl/pull/18025 (not merged)
Ref: https://github.com/curl/curl/pull/12079 (not merged)
Ref: https://github.com/curl/curl/issues/12076