cares: fix missing `bool` on mac with gcc [ci skip]
```
In file included from /Users/runner/work/curl-for-win/curl-for-win/cares/src/lib/event/ares_event_configchg.c:386:
/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/notify.h:336:11: error: unknown type name 'bool'
  336 | OS_EXPORT bool notify_is_valid_token(int val)
      |           ^~~~
```
https://github.com/curl/curl-for-win/actions/runs/12970604191/job/36176027186#step:3:2614