GHA: disable zizmor audit needing `api.github.com` access [ci skip]
Fixing:
```
fatal: no audit was performed
'known-vulnerable-actions' audit failed on file://.github/workflows/build.yml

Caused by:
    0: error in 'known-vulnerable-actions' audit
    1: request error while accessing GitHub API
    2: Cache error: Cache error: error sending request for url (https://api.github.com/advisories?ecosystem=actions&affects=actions%2Fcheckout%40v7.0.1)
Error: Process completed with exit code 1.
```
Ref: https://github.com/curl/curl-for-win/actions/runs/34418653667/job/102689051688

It'd be nice to be able to have a per-workflow and/or per-job egress
allowlist. With the global list, one non-critical tool may lower the
security and effectivenes of the firewall, or needs workarounds like
this, which is also undesired due to maintenance and lowering the
effectiveness of zizmor in this particular case.

Notice that `impostor_commit` may also access `api.github.com`, but only
if it falls of the fast codepath, which does not happen in practice at
the moment. If it happens in the future, this audit needs to be disabled
too (if we end up using the egress firewall feature.)

Ref: https://docs.zizmor.sh/configuration/#rules-id-disable