install musl packages for linux
`linux-headers` package required to fix openssl builds to avoid:
```
../crypto/mem_sec.c:60:13: fatal error: linux/mman.h: No such file or directory
   60 | #   include <linux/mman.h>
      |             ^~~~~~~~~~~~~~
```

Alternative workarounds:
- disable 'secure-memory' feature with `no-secure-memory` `./Configure` option
- CC="${CC} -static -idirafter /usr/include/ -idirafter /usr/include/$(uname -m)-linux-gnu/"

Ref: https://github.com/openssl/openssl/issues/7207#issuecomment-880121450