wolfssl-cmake.sh: add cmake build (but still broken) [ci skip]
On the bright side: CMake builds were fixed in a recent wolfSSL
update.

At the same time the codebase got broken and no longer builds with
either autotools or cmake, due to a missing type `sp_int_word`:

  ./wolfssl/wolfcrypt/src/sp_int.c:5630:5: error: use of undeclared identifier 'sp_int_word'

Its declaration is guarded with PP conditions that are always
false when building with mingw-w64 for 64-bit CPUs.

The code also assumes that `_MSC_VER` is always defined, and that
`#pragma comment(lib, "crypt32")` always works. These only work with
MSVC compilers though.