libssh2.sh: adapt to upstream moving to "curldown" docs [ci skip]
Upstream replaced `.3` source files with `.md` "curldown" ones.
Simplify the copying process and avoid the new script that was
picked up by `lido`, causing the job to fail.

Fixing:
```
+ read -r d
+ lipo -create -output curl-8.17.0-DEV_20251009-universal-macos/dep/libssh2/docs/cd2nroff.txt ./curl-8.17.0-DEV_20251009-aarch64-macos/dep/libssh2/docs/cd2nroff.txt ./curl-8.17.0-DEV_20251009-x86_64-macos/dep/libssh2/docs/cd2nroff.txt
fatal error: /Applications/Xcode_16.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't figure out the architecture type of: ./curl-8.17.0-DEV_20251009-aarch64-macos/dep/libssh2/docs/cd2nroff.txt
+ rm -r -f /Users/runner/work/curl-for-win/curl-for-win/.cw-gpg
Error: Process completed with exit code 1.
```
Ref: https://github.com/curl/curl-for-win/actions/runs/18388441115/job/52392670105#step:3:10158

Ref: https://github.com/libssh2/libssh2/commit/b889b39945ae1a47858a3bb85e21e8c174271baf
Ref: https://github.com/libssh2/libssh2/pull/1660